import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)
const STORAGE_KEY = 'pfl_lang'

// ── Translations ────────────────────────────────────────────────────────
const i18n = {
  en: {
    // ── Common (shared across pages) ──────────────────────────────────
    common: {
      info: 'Info',
      themeSettings: 'Theme Settings',
      reset: 'Reset',
      create: 'Create',
      delete: 'Delete',
      save: 'Save',
      add: 'Add',
      edit: 'Edit',
      close: 'Close',
      cancel: 'Cancel',
      complete: 'Complete',
      open: 'Open',
      closed: 'Closed',
      finished: 'Finished',
      live: 'Live',
      joining: 'Joining',
      copyObs: 'Copy OBS URL',
      copied: 'Copied!',
      overlayPreview: 'Overlay Preview',
      username: 'Username',
      game: 'Game',
      winner: 'Winner',
      noResults: 'No results for',
      search: 'Search...',
      // Theme settings shared
      background: 'Background',
      opacity: 'Opacity',
      blur: 'Blur',
      accentColor: 'Accent Color',
      textColor: 'Text Color',
      layout: 'Layout',
      borderRadius: 'Border Radius',
      padding: 'Padding',
      borderWidth: 'Border Width',
      font: 'Font',
      fontSize: 'Font Size',
      fontFamily: 'Font Family',
      mono: 'Mono',
      sans: 'Sans',
      inter: 'Inter',
      serif: 'Serif',
      showBorder: 'Show Border',
      glowEffect: 'Glow Effect', overlayScale: 'Overlay Scale',
      visibilityEffects: 'Visibility & Effects',
      displayEffects: 'Display & Effects',
      maxEntries: 'Max Entries',
      clearAll: 'Clear All',
    },

    // ── Landing page ──────────────────────────────────────────────────
    landing: {
      nav: { features: 'Features', pricing: 'Pricing', setup: 'Setup', cta: 'Register Free' },
      hero: {
        label: 'The Casino Streaming Platform',
        title1: 'Stream Like a', title2: 'High Roller',
        sub: 'OBS overlays, Twitch bot, bonus hunt tracking, tournaments, viewer loyalty — everything a casino streamer needs, in one platform.',
        cta1: 'Register Free', cta2: 'Explore',
      },
      marquee: ['OBS Overlays', 'Twitch Bot', 'Bonus Hunts', 'Tournaments', 'Boss Fights', 'Slot Requests', 'Personal Bests', 'Predictions', 'Points Battle', 'Stream Points', 'Hot Words', 'Website Builder', 'Casino Deals', 'Live Chat'],
      stats: [
        { value: '14+', label: 'Stream Tools' },
        { value: '10+', label: 'OBS Overlays' },
        { value: '100%', label: 'Free to Start' },
      ],
      featuresSection: {
        label: 'Features', title: 'Everything You Need to Stream',
        items: [
          { t: 'Wager Tracker', d: 'Dynamic wager progress with color-shifting bar and live multiplier.' },
          { t: 'Bonus Hunt', d: 'Full tracker with buy-in, auto multipliers, and Required X.' },
          { t: 'Tournaments', d: 'Bracket system for up to 32 players with spinning wheel.' },
          { t: 'Boss Fight', d: 'Gauntlet mode — boss vs challengers in sequential duels.' },
          { t: 'Slot Requests', d: 'Viewers request games via !sr. Raffle picks the winner.' },
          { t: 'Personal Bests', d: 'Auto leaderboard from your bonus hunt history.' },
          { t: 'Points Battle', d: 'Betting pools where viewers wager via !bet command.' },
          { t: 'Stream Points', d: 'Loyalty system with earning, leaderboards, and store.' },
          { t: 'Predictions', d: 'Number guessing + A vs B voting with live overlays.' },
          { t: 'Hot Words', d: 'Real-time chat word frequency with badge overlay.' },
          { t: 'Twitch Bot', d: 'Built-in IRC bot with all commands and chat relay.' },
          { t: 'Website Builder', d: 'Personal streamer page with casino deals.' },
          { t: 'Join Raffle', d: 'Viewers join, you spin. Animated winner reveal.' },
          { t: 'Live Chat', d: 'Chat overlay with role badges. Twitch + Kick.' },
        ],
      },
      why: {
        label: 'Why Pulseframelabs', title: 'Built Different',
        items: [
          { title: 'All-in-One Platform', desc: 'No more juggling 5 different tools. Overlays, bot, points, website — everything lives in one dashboard. Configure once, stream everywhere.' },
          { title: 'Real-Time Everything', desc: 'Every overlay updates instantly. When you pick a tournament winner, adjust wager progress, or a viewer places a bet — the overlay reflects it live. Zero delay.' },
          { title: 'Viewer Interaction', desc: 'Your audience is part of the show. They join tournaments, request slots, place bets, vote on predictions, and earn points — all through simple chat commands.' },
          { title: 'Professional Overlays', desc: '10+ themed OBS overlays that look premium out of the box. Wager bars, bracket trees, boss fight gauntlets, chat displays, hot word clouds — all customizable.' },
          { title: 'Built-in Twitch Bot', desc: 'No external bot needed. Our IRC bot handles !sr, !join, !bet, !vote, !points, plus custom commands. Connects in seconds with OAuth.' },
          { title: 'Your Own Website', desc: 'Create a personal streamer landing page with casino deals, social links, and a particle-animated background. Share one link for everything.' },
        ],
      },
      commands: {
        label: 'Chat Commands', title: 'Your Viewers Drive the Action',
        sub: 'Simple chat commands that anyone can use. No setup required for viewers.',
        items: [
          { cmd: '!sr', args: 'GameName', desc: 'Request a slot game for the streamer to play' },
          { cmd: '!join', args: 'GameName', desc: 'Join a tournament, boss fight, or raffle session' },
          { cmd: '!bet', args: 'option amount', desc: 'Place a points bet in an active points battle' },
          { cmd: '!vote', args: 'a / b', desc: 'Vote on a prediction wall (Option A or B)' },
          { cmd: '!points', args: '', desc: 'Check your current point balance' },
          { cmd: '!sr cancel', args: '', desc: 'Cancel your slot request from the queue' },
        ],
      },
      setupSection: {
        label: 'Setup', title: 'From Zero to Live Stream',
        items: [
          { n: '01', t: 'Create Account', d: 'Sign up free in seconds. No credit card required.', time: '30s' },
          { n: '02', t: 'Connect Twitch', d: 'Link your channel with an OAuth token via the setup wizard.', time: '1min' },
          { n: '03', t: 'Configure Tools', d: 'Set up overlays, bot commands, and features from the dashboard.', time: '1min' },
          { n: '04', t: 'Add Overlays', d: 'Copy overlay URLs into OBS as browser sources. Fully themed.', time: '30s' },
          { n: '05', t: 'Engage Viewers', d: 'Viewers interact via !join, !sr, !bet, !vote commands in chat.', time: 'Live' },
          { n: '06', t: 'Go Live', d: 'Start streaming. All overlays update in real-time as you play.', time: 'Ready' },
        ],
      },
      pricing: {
        label: 'Pricing', title: 'Choose Your Plan',
        sub: 'Buy credits, choose your plan. All features included in every package.',
        trial: 'Trial', trialDesc: 'Test all features for 24 hours',
        monthly: 'Monthly', monthlyDesc: 'Full access, cancel anytime',
        quarterly: 'Quarterly', quarterlyDesc: 'Save 15% — most flexible',
        halfYear: 'Half Year', halfYearDesc: 'Save 25% — best value',
        annual: 'Annual', annualDesc: 'Save 35% — ultimate deal',
        perMonth: '/mo', save: 'Save',
        credits: 'Credits',
        day: '1 Day', month: '1 Month', months3: '3 Months', months6: '6 Months', months12: '12 Months',
        allFeatures: 'All Features Included',
        features: ['All 14+ Stream Tools', 'All 10+ OBS Overlays', 'Twitch Bot with all Commands', 'Website Builder', 'Unlimited Tournaments & Boss Fights', 'Stream Points & Store System'],
        popular: 'Most Popular',
        cryptoNote: 'Buy credits with cryptocurrency — then activate your plan',
        howItWorks: 'How It Works',
        step1: 'Register for free & explore the dashboard',
        step2: 'Buy credits with crypto (BTC, ETH, USDT...)',
        step3: 'Choose a plan & activate with your credits',
        step4: 'All overlay links & features unlock instantly',
        choosePlan: 'Choose Plan',
        registerFree: 'Register Free',
        freeNote: 'Free registration — explore all features. Overlay links unlock after purchasing a plan with credits.',
      },
      ctaSection: {
        label: 'Get Started', title: 'Ready to Go All In?',
        sub: 'Register for free, explore the dashboard, and unlock everything with credits when you\'re ready.',
        cta: 'Register Free Now',
      },
      footer: 'All rights reserved.',

      // Testimonials
      testimonials: {
        label: 'Trusted by Streamers', title: 'What Streamers Say',
        items: [
          { name: 'CasinoKing', role: 'Casino Streamer', text: 'Pulseframelabs replaced 5 different tools for me. The overlays look insane and the bot just works.' },
          { name: 'SlotMaster', role: 'Slot Streamer', text: 'The bonus hunt tracker alone is worth it. My viewers love the tournament bracket overlay.' },
          { name: 'HighRollerTV', role: 'Casino Streamer', text: 'Setup took 5 minutes. The website builder saved me from hiring a developer. Highly recommended.' },
        ],
      },

      // FAQ
      faq: {
        label: 'FAQ', title: 'Frequently Asked Questions',
        items: [
          { q: 'How does the payment work?', a: 'You buy credits with cryptocurrency (BTC, ETH, LTC, USDT). Credits are added instantly after blockchain confirmation. Then you activate a plan with your credits.' },
          { q: 'Can I cancel anytime?', a: 'There is no recurring subscription. You buy a plan once and it runs until it expires. No auto-renewal, no hidden fees.' },
          { q: 'Which OBS version is supported?', a: 'Any version of OBS Studio that supports browser sources. Simply copy the overlay URL and add it as a browser source.' },
          { q: 'Can I try before I buy?', a: 'Yes! Register for free and explore the entire dashboard. Overlay links are unlocked after purchasing a plan.' },
          { q: 'How many overlays can I use?', a: 'All plans include every overlay and feature. There are no tier restrictions — you get everything.' },
          { q: 'Is my data private?', a: 'Yes. Every user has isolated data with Row Level Security. No one can see your settings, overlays, or configurations.' },
        ],
      },

      // Live Counter
      liveCounter: {
        label: 'Community', title: 'Growing Every Day',
        streamers: 'Registered Streamers',
        overlays: 'Overlays Created',
        uptime: 'Uptime',
      },

      // Comparison
      comparison: {
        label: 'Compare', title: 'Free vs. Premium',
        free: 'Free', premium: 'Premium',
        features: [
          { name: 'Dashboard Access', free: true, premium: true },
          { name: 'All 14+ Stream Tools', free: true, premium: true },
          { name: 'OBS Overlay Links', free: false, premium: true },
          { name: 'Twitch Bot Connection', free: false, premium: true },
          { name: 'Public Streamer Page', free: false, premium: true },
          { name: 'Website Builder', free: false, premium: true },
          { name: 'Store / Points System', free: false, premium: true },
          { name: 'Theme Customization', free: true, premium: true },
          { name: 'Priority Support', free: false, premium: true },
        ],
      },
    },

    // ── Login page ────────────────────────────────────────────────────
    login: {
      welcomeBack: 'Welcome back',
      getStarted: 'Get started',
      signInSub: 'Sign in to access your streaming dashboard',
      registerSub: 'Create your account in seconds',
      signIn: 'Sign In',
      register: 'Register',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      username: 'Username',
      emailPlaceholder: 'your@email.com',
      passwordPlaceholder: 'Enter your password',
      createPasswordPlaceholder: 'Create a strong password',
      repeatPasswordPlaceholder: 'Repeat your password',
      usernamePlaceholder: 'Your display name',
      signInBtn: 'Sign In',
      createAccountBtn: 'Create Account',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      terms: 'By continuing you agree to our Terms of Service',
      platformOverview: 'Platform Overview',
      videoSoon: 'Video coming soon',
      pwLength: 'At least 8 characters',
      pwUppercase: '1 uppercase letter (A-Z)',
      pwSpecial: '1 special character (!@#...)',
      pwNoMatch: 'Passwords do not match',
      usernameRequired: 'Username is required',
      emailRequired: 'Email is required',
      pwRequirements: 'Password does not meet requirements',
      emailSent: 'Confirmation email sent!',
      emailSentDesc: 'We sent a confirmation link to your email address. Please check your inbox and click the link to activate your account.',
      checkSpam: 'Not received? Check your spam folder.',
      resend: 'Resend email',
      resent: 'Email resent!',
      emailNotConfirmed: 'Your email address has not been confirmed yet. Please check your inbox.',
      backToLogin: 'Back to Sign In',
    },

    // ── Sidebar ───────────────────────────────────────────────────────
    sidebar: {
      dashboard: 'Dashboard', overlays: 'Overlays', community: 'Community', stream: 'Stream',
      wagerBar: 'Wager Bar', personalBests: 'Personal Bests', slotRequests: 'Slot Requests',
      bonushunt: 'Bonushunt', tournaments: 'Tournaments', bossFight: 'Boss Fight',
      hotWords: 'Hot Words', predictions: 'Predictions', join: 'Join', chat: 'Chat',
      twitchBot: 'Twitch Bot', pointsBattle: 'Points Battle', streamPoints: 'Stream Points',
      website: 'Website', shop: 'Shop', credits: 'Credits',
      lightMode: 'Light Mode', darkMode: 'Dark Mode', signOut: 'Sign out',
    },

    // ── Shop ──────────────────────────────────────────────────────────
    shop: {
      title: 'Shop',
      creditBalance: 'Credit Balance', credits: 'Credits',
      buyCredits: 'Buy Credits',
      cryptoNote: 'Pay with cryptocurrency — credits are added after confirmation.',
      plans: 'Subscription Plans', activePlan: 'Active Plan',
      noPlan: 'No active plan',
      activate: 'Activate', activated: 'Activated!',
      insufficientCredits: 'Not enough credits',
      expiresIn: 'Expires in', days: 'days',
      transactionHistory: 'Transaction History',
      purchase: 'Credit Purchase', planActivation: 'Plan Activation',
      trial: 'Trial', monthly: 'Monthly', quarterly: 'Quarterly', halfYear: 'Half Year', annual: 'Annual',
      trialDesc: '1 Day Access', monthlyDesc: '30 Days Access', quarterlyDesc: '90 Days Access',
      halfYearDesc: '180 Days Access', annualDesc: '365 Days Access',
      activateToUnlock: 'Activate a plan to unlock',
      urlHidden: 'Subscribe to reveal your OBS URL',
      pageNotAvailable: 'This page is not available. The owner has no active subscription.',
      payWithCrypto: 'Pay with BTC, ETH, LTC, USDT',
      selectCoin: 'Select Cryptocurrency',
      generating: 'Generating address...',
      generateAddress: 'Generate Payment Address',
      sendPayment: 'Send Payment',
      amountToPay: 'Amount to pay',
      sendTo: 'Send to this address',
      copyLabel: 'Copy', copiedLabel: 'Copied',
      waitingPayment: 'Waiting for payment confirmation...',
      autoCredit: 'Credits will be added automatically after confirmation.',
    },

    // ── Dashboard ─────────────────────────────────────────────────────
    dashboard: {
      morning: 'Good Morning', afternoon: 'Good Afternoon', evening: 'Good Evening',
      welcomeMsg: 'We wish you good luck and success on a new streaming day!',
      supportMsg: 'For questions, please reach out to our support via the live chat at the bottom right of the screen.',
      quickActions: 'Quick Actions',
      actions: {
        wagerBar: 'Track wager progress', personalBests: 'View best wins', slotRequests: 'Manage slot requests',
        bonushunt: 'Create bonus hunts', tournaments: 'Host tournaments', bossFight: 'Start gauntlet mode',
        hotWords: 'Track chat words', predictions: 'Guessing & Voting', join: 'Viewer raffle',
        chat: 'Live Chat Overlay', twitchBot: 'Bot connection & commands', pointsBattle: 'Viewer betting with points',
        streamPoints: 'Points system & store', website: 'Build your streamer website',
      },
    },

    // ── Wager Bar ─────────────────────────────────────────────────────
    wager: {
      title: 'Wager Bar',
      infoText: 'Track your wager progress for casino bonuses. Enter deposit, bonus, and wager target. The progress bar shows live status and changes color (red to orange to green). Multiplier and remaining amount are calculated automatically.',
      newWager: 'New Wager',
      newWagerSession: 'New Wager Session',
      casinoName: 'Casino Name *',
      bonusType: 'Bonus Type',
      nonSticky: 'Non-Sticky', sticky: 'Sticky',
      currency: 'Currency',
      depositAmount: 'Deposit Amount',
      bonusAmount: 'Bonus Amount',
      wagerAmount: 'Wager Amount',
      noSessions: 'No wager sessions yet. Create your first one above.',
      valueColors: 'Value Colors', win: 'Win', loss: 'Loss',
    },

    // ── Personal Bests ────────────────────────────────────────────────
    personalBests: {
      title: 'Personal Bests',
      infoText: 'Automatically shows the best wins per game from all bonus hunts. Entries are grouped by game name — for each game, the highest win and number of appearances are displayed. The overlay can be embedded as a browser source in OBS.',
      totalGames: 'Total Games', bestWin: 'Best Win', totalPlays: 'Total Plays', avgWin: 'Ø Win',
      highestWin: 'Highest Win', mostPlayed: 'Most Played',
      searchGame: 'Search game...',
      colGame: 'Game', colBestWin: 'Best Win', colAppearances: 'Appearances', colWinBar: 'Win Bar',
      empty: 'No wins in bonus hunts yet. Create a bonus hunt and enter wins.',
    },

    // ── Slot Requests ─────────────────────────────────────────────────
    slotRequests: {
      title: 'Slot Requests',
      infoText: 'Viewers can submit slot requests via !sr GameName in chat. The list shows all requests. Use the Raffle button to randomly select a game. You can open/close requests and clear the list at any time.',
      newRequest: 'New Request',
      viewerName: 'Viewer Name',
      egGame: 'e.g. Sweet Bonanza',
      raffle: 'Raffle', rolling: 'Rolling...', reRoll: 'Re-Roll',
      confirmClear: 'Confirm & Clear List', confirmKeep: 'Confirm & Keep',
      empty: 'No slot requests. Add manually or use !sr in chat.',
      pendingTotal: 'Pending / Total', won: 'Won',
      raffleInProgress: 'Raffle in progress...',
    },

    // ── Bonushunt ─────────────────────────────────────────────────────
    bonushunt: {
      title: 'Bonushunt',
      infoText: 'Manage your bonus hunts with start balance, buy-in per game, and automatic multiplier calculation. The overlay shows live progress, required X, and the current status. Embedded as a browser source in OBS.',
      newBonushunt: 'New Bonus Hunt',
      huntName: 'Hunt name',
      startBalance: 'Start balance',
      completed: 'Completed',
      empty: 'No bonus hunts yet. Create your first one above.',
      showTitle: 'Show Title', showProfit: 'Show Profit',
      showTotalWin: 'Show Total Win', showNumbers: 'Show Numbers',
      valueColors: 'Value Colors', win: 'Win', loss: 'Loss',
    },

    // ── Tournaments ───────────────────────────────────────────────────
    tournaments: {
      title: 'Tournament',
      infoText: 'Create tournaments with up to 32 players. Viewers can join via !join GameName in chat. After the join phase, players are placed into the bracket. Click the trophy icon to advance winners. The overlay shows the complete bracket tree live.',
      newTournament: 'New Tournament',
      tournamentName: 'Tournament name',
      participants4: '4 Participants', participants8: '8 Participants',
      participants16: '16 Participants', participants32: '32 Participants',
      participants: 'Participants', gameName: 'Game Name',
      noParticipants: 'No participants yet. Add manually or let viewers use !join in chat.',
      luckyWheel: 'Lucky Wheel', setBoss: 'Set Boss',
      startTournament: 'Start Tournament',
      champion: 'Champion:', winnerLabel: 'Winner:',
      clickTrophy: 'Click the trophy icon next to a player in the overlay to select the winner.',
      empty: 'No tournaments yet. Create your first one above.',
      highlightFinal: 'Highlight / Final',
      showPrizePool: 'Show Prize Pool', showSlots: 'Show Slots', showStatus: 'Show Status',
    },

    // ── Boss Fight ────────────────────────────────────────────────────
    bossfight: {
      title: 'Boss Fight',
      infoText: 'Boss Fight in gauntlet mode: A boss fights against multiple challengers in 1v1 duels. The boss starts with as many lives as there are challengers. Viewers join via !join GameName. After starting, you decide each duel with Boss Wins / Challenger Wins.',
      newBossfight: 'New Boss Fight',
      name: 'Name',
      addParticipant: 'Add Participant',
      participants: 'Participants',
      noParticipants: 'No participants yet. Add manually or let viewers type !join GameName in chat.',
      setBoss: 'Set Boss', startFight: 'Start Fight', luckyWheel: 'Lucky Wheel',
      currentDuel: 'Current Duel', challenger: 'Challenger', vs: 'VS', boss: 'Boss',
      bossWins: 'Boss Wins', challengerWins: 'Challenger Wins',
      bossLives: 'Boss Lives:', score: 'Score: Players',
      duelHistory: 'Duel History',
      bossWon: 'Boss Won', challengerWon: 'Challenger Won',
      bossWinsTitle: 'BOSS WINS!', playersWinTitle: 'PLAYERS WIN!',
      finalScore: 'Final Score: Players',
      completeRemove: 'Complete & Remove',
      empty: 'No boss fights yet. Create your first one above.',
    },

    // ── Hot Words ─────────────────────────────────────────────────────
    hotwords: {
      title: 'Hot Words',
      infoText: 'Hot Words automatically tracks the most frequent words from Twitch chat. The bot counts every word in every message. Use the word filter to exclude unwanted words.',
      empty: 'No Hot Words. Connect the Twitch bot to track chat words.',
      totalWords: 'Total Words', totalMentions: 'Total Mentions', topWord: 'Top Word',
      wordList: 'Word List', clearAll: 'Clear All',
      wordFilter: 'Word Filter', excludedWords: 'Excluded Words',
      filterPlaceholder: 'word1, word2, word3',
      maxEntries: 'Max Entries',
    },

    // ── Predictions ───────────────────────────────────────────────────
    predictions: {
      title: 'Predictions',
      infoText: 'Predictions offers two modes: In the guessing game, viewers guess a number via chat — the closest guess wins. In the prediction wall, viewers vote on two options. Both modes can be embedded as overlays in OBS.',
      newPrediction: 'New Prediction',
      guessingGame: 'Guessing Game', predictionWall: 'Prediction Wall',
      noActive: 'No active prediction. Create a new one above.',
      noActiveGuess: 'No active guessing game. Create one with the button above.',
      guessesReceived: 'guesses received',
      number: 'Number', targetValue: 'Target Value', resolve: 'Resolve',
      results: 'Results', newGuessingGame: 'New Guessing Game',
      question: 'Question', egWho: 'e.g. Who wins?',
      optionA: 'Option A', optionB: 'Option B',
      startPrediction: 'Start Prediction', lockVoting: 'Lock Voting',
      optionAWins: 'Option A wins', optionBWins: 'Option B wins',
    },

    // ── Join ──────────────────────────────────────────────────────────
    join: {
      title: 'Join',
      infoText: 'Open a join session and viewers can participate via !join in chat. After closing, a winner is randomly drawn — with an animated name display in the overlay.',
      newJoin: 'New Join',
      noActive: 'No active join session. Create a new one above.',
      closeJoin: 'Close !join', drawWinner: 'Draw Winner', newRound: 'New Round',
      drawing: 'Drawing...',
      participants: 'Participants',
      noParticipants: 'No participants yet. Viewers can join via !join in chat.',
      addManually: 'Add Manually',
    },

    // ── Chat ──────────────────────────────────────────────────────────
    chat: {
      title: 'Live Chat Overlay',
      infoText: 'This overlay reads the chat live and also integrates the Kick chat via Restream. It is embedded directly in OBS as a browser source — your viewers do not see this dashboard, only the overlay on the stream.',
      newChat: 'New Chat',
      name: 'Name',
      empty: 'No chats yet. Create your first one above.',
      chatEffects: 'Chat & Effects', maxMessages: 'Max Messages',
    },

    // ── Twitch Bot ────────────────────────────────────────────────────
    twitchBot: {
      title: 'Twitch Bot',
      infoText: 'Connect your Twitch channel via IRC and OAuth token. The bot reads chat, responds to commands (!sr, !join) and relays messages to overlays. Custom commands and feature toggles can be managed here.',
      newBot: 'New Twitch Bot',
      twitchChannel: 'Twitch Channel',
      enterChannel: 'Enter your channel name',
      channelName: 'Channel Name *', channelPlaceholder: 'your_twitch_channel',
      botUsername: 'Bot Username (optional)', botPlaceholder: 'bot_account (empty = same as channel)',
      botHint: 'If you have a separate bot account, enter it here.',
      next: 'Next', back: 'Back', completeSetup: 'Complete Setup',
      setupChannel: 'Set up channel',
      oauthToken: 'OAuth Token', oauthSetup: 'Set up bot access',
      oauthInfo: 'The OAuth token allows the bot to write messages on your behalf and react to chat events. Generate it at twitchapps.com/tmi and paste it here.',
      oauthPlaceholder: 'oauth:xxxxxxxxxxxxxxx',
      oauthLocal: 'The token is stored locally only and not shared.',
      empty: 'No Twitch Bot set up yet. Create your first one above.',
      connection: 'Connection', channel: 'Channel',
      connect: 'Connect', disconnect: 'Disconnect',
      featureToggles: 'Feature Toggles',
      chatRelay: 'Chat Relay', chatRelayDesc: 'Relay all Twitch chat messages to overlays',
      slotRequestsToggle: 'Slot Requests', slotRequestsDesc: 'Handle !sr <game> commands from viewers',
      quickGuesses: 'Quick Guesses', quickGuessesDesc: 'Handle guess commands from viewers',
      pointsBattleToggle: 'Points Battle', pointsBattleDesc: 'Handle !bet commands for predictions',
      loyaltyGiveaways: 'Loyalty Giveaways', loyaltyGiveawaysDesc: 'Track keyword entries for giveaways',
      customCommands: 'Custom Commands',
      commandPlaceholder: '!command', responsePlaceholder: 'Response text',
      noCommands: 'No commands yet.',
      liveFeed: 'Live Feed', clear: 'Clear',
      connectToSee: 'Connect the bot to see live chat.',
      connectTwitch: 'Connect with Twitch',
      twitchConnected: 'Twitch connected successfully',
    },

    // ── Points Battle ─────────────────────────────────────────────────
    pointsBattle: {
      title: 'Points Battle',
      infoText: 'Create a prediction battle with custom options. Viewers bet points using !bet keyword amount in chat. When the timer runs out, bets are locked. Set up at least 2 options with unique keywords.',
      newBattle: 'New Battle', newPointsBattle: 'New Points Battle',
      options: 'Options (min 2)',
      keywordPlaceholder: 'Keyword (e.g. red)', labelPlaceholder: 'Label (e.g. Team Red)',
      addOption: '+ Add option',
      minPoints: 'Min Points', maxPoints: 'Max Points', duration: 'Duration (sec)',
      startBattle: 'Start Battle',
      noActive: 'No active battle. Create one above.',
      stop: 'Stop', totalPool: 'Total Pool', bettors: 'Bettors',
      command: 'Command', bets: 'bets', pts: 'pts',
      recentBets: 'Recent Bets',
    },

    // ── Stream Points ─────────────────────────────────────────────────
    streamPoints: {
      title: 'Stream Points & Store',
      infoText: 'Manage viewer points and a store. Viewers earn points through watch time and interactions. They can check their balance with !points in chat. Create store items that viewers can redeem with their points.',
      newStreamPoints: 'New Stream Points',
      empty: 'No stream points configured yet. Create your setup above.',
      points: 'Points', store: 'Store',
      pointsConfig: 'Points Configuration',
      pointsPerMinute: 'Points per Minute', pointsPerFollow: 'Points per Follow', pointsPerSub: 'Points per Sub',
      viewers: 'Viewers', totalPoints: 'Total Points',
      noViewers: 'No viewers. They register with !points in chat.',
      newStoreItem: 'New Store Item', addStoreItem: 'Add Store Item',
      itemName: 'Item Name *', egItem: 'e.g. VIP Badge',
      pricePoints: 'Price (Points) *',
      quantity: 'Quantity (-1 = unlimited)',
      visible: 'Visible', hidden: 'Hidden',
      description: 'Description', itemDesc: 'Item description...',
      createItem: 'Create Item', storeItems: 'Store Items',
      noStoreItems: 'No store items. Add one above.',
      unlimited: '∞', left: 'left',
      redemptions: 'Redemptions',
      completed: 'completed', refunded: 'refunded', pending: 'pending',
      itemImage: 'Item Image', imageHint: 'PNG/JPG, max 512 KB',
    },

    // ── Website ───────────────────────────────────────────────────────
    website: {
      branding: 'Branding', colors: 'Colors', icon: 'Icon',
      sections: 'Sections', socials: 'Socials', deals: 'Deals', preview: 'Preview',
      websiteTitle: 'Website Title *', egStreamer: 'e.g. StreamerName',
      tagline: 'Tagline', egTagline: 'e.g. Casino Streamer & Content Creator',
      colorTheme: 'Color Theme',
      gold: 'Gold', purple: 'Purple', blue: 'Blue', emerald: 'Emerald',
      red: 'Red', cyan: 'Cyan', pink: 'Pink', orange: 'Orange',
      customColor: 'Custom Primary Color',
      chooseIcon: 'Choose Icon',
      globe: 'Globe', gamepad: 'Gamepad', zap: 'Zap', crown: 'Crown',
      star: 'Star', diamond: 'Diamond', flame: 'Flame', trophy: 'Trophy',
      uploadIcon: 'Or Upload Custom Icon',
      uploadHint: 'Recommended size: 128 x 128 px — Min: 64x64 px, Max: 512x512 px. PNG or SVG with transparent background.',
      clickUpload: 'Click to upload (PNG, SVG)',
      iconUploaded: 'Icon uploaded', removeIcon: 'Remove custom icon',
      websiteSections: 'Website Sections',
      aboutMe: 'About Me', aboutMeDesc: 'Short bio and introduction',
      schedule: 'Stream Schedule', scheduleDesc: 'Weekly streaming times',
      socialLinks: 'Social Links', socialLinksDesc: 'Twitch, YouTube, Twitter, etc.',
      stats: 'Stats', statsDesc: 'Follower count, stream hours',
      gallery: 'Gallery', galleryDesc: 'Clips and highlights',
      donate: 'Donate', donateDesc: 'Donation link and goals',
      casinoDeals: 'Casino Deals', casinoDealsDesc: 'Casino offers and bonus deals',
      twitch: 'Twitch', youtube: 'YouTube', twitter: 'Twitter/X',
      instagram: 'Instagram', discord: 'Discord', tiktok: 'TikTok', kick: 'Kick',
      myWebsite: 'My Website', welcomeStream: 'Welcome to my stream', playNow: 'Play Now',
      newWebsite: '+ New Website', editWebsite: 'Edit Website', reset: 'Reset', cancel: 'Cancel', saveWebsite: 'Save Website',
      websiteBuilder: 'Website Builder',
      websiteBuilderInfo: 'Create your personal streamer landing page with casino deals, social links, and a custom design. Your page is publicly accessible and can be shared with one link.',
      empty: 'No website created yet. Click "+ New Website" to start.',
      copy: 'Copy', open: 'Open', websitePreview: 'Live Preview', primaryColor: 'Primary Color',
      casinoDealsInfo: 'Add casino deals with logos, links, and custom button text. These will be displayed on your public streamer page.',
      addDeal: 'Add New Deal',
      casinoLogo: 'Casino Logo (max 200 KB)',
      chooseImage: 'Click to upload image',
      dealHeadline: 'Casino Name / Headline',
      dealBtnText: 'Button Text (default: Play Now)',
      dealLinkUrl: 'Affiliate Link URL',
      untitledDeal: 'Untitled Deal',
      noLink: 'No link set',
      bgColor: 'Background Color',
      textColorSite: 'Text Color',
      accentColorSite: 'Accent Color',
      particles: 'Particle Animation',
      showNavbar: 'Show Navigation',
      showFooter: 'Show Footer',
      navBlur: 'Navigation Blur',
      navStyle: 'Navigation Style',
      aboutPlaceholder: 'Write a short bio about yourself...',
      scheduleDay: 'Day', scheduleTime: 'Time', addScheduleEntry: 'Add Entry',
      statLabel: 'Label', statValue: 'Value', addStat: 'Add Stat',
      galleryUrl: 'Image or Clip URL', addGalleryItem: 'Add Image/Clip',
      donateLink: 'Donation Link URL', donateText: 'Donation info text...',
    },
  },

  de: {
    // ── Common ────────────────────────────────────────────────────────
    common: {
      info: 'Info',
      themeSettings: 'Theme-Einstellungen',
      reset: 'Zurücksetzen',
      create: 'Erstellen',
      delete: 'Löschen',
      save: 'Speichern',
      add: 'Hinzufügen',
      edit: 'Bearbeiten',
      close: 'Schließen',
      cancel: 'Abbrechen',
      complete: 'Abschließen',
      open: 'Offen',
      closed: 'Geschlossen',
      finished: 'Beendet',
      live: 'Live',
      joining: 'Beitreten',
      copyObs: 'OBS-URL kopieren',
      copied: 'Kopiert!',
      overlayPreview: 'Overlay-Vorschau',
      username: 'Benutzername',
      game: 'Spiel',
      winner: 'Gewinner',
      noResults: 'Keine Ergebnisse für',
      search: 'Suchen...',
      background: 'Hintergrund',
      opacity: 'Deckkraft',
      blur: 'Unschärfe',
      accentColor: 'Akzentfarbe',
      textColor: 'Textfarbe',
      layout: 'Layout',
      borderRadius: 'Eckenradius',
      padding: 'Innenabstand',
      borderWidth: 'Rahmenbreite',
      font: 'Schrift',
      fontSize: 'Schriftgröße',
      fontFamily: 'Schriftart',
      mono: 'Mono',
      sans: 'Sans',
      inter: 'Inter',
      serif: 'Serif',
      showBorder: 'Rahmen anzeigen',
      glowEffect: 'Leuchteffekt', overlayScale: 'Overlay-Größe',
      visibilityEffects: 'Sichtbarkeit & Effekte',
      displayEffects: 'Anzeige & Effekte',
      maxEntries: 'Max. Einträge',
      clearAll: 'Alle löschen',
    },

    // ── Landing page ──────────────────────────────────────────────────
    landing: {
      nav: { features: 'Features', pricing: 'Preise', setup: 'Setup', cta: 'Kostenlos registrieren' },
      hero: {
        label: 'Die Casino-Streaming-Plattform',
        title1: 'Streame wie ein', title2: 'High Roller',
        sub: 'OBS-Overlays, Twitch-Bot, Bonushunt-Tracking, Turniere, Viewer-Loyalität — alles was ein Casino-Streamer braucht, auf einer Plattform.',
        cta1: 'Kostenlos registrieren', cta2: 'Entdecken',
      },
      marquee: ['OBS-Overlays', 'Twitch-Bot', 'Bonushunts', 'Turniere', 'Bossfights', 'Slot-Anfragen', 'Persönliche Bestleistungen', 'Vorhersagen', 'Punkte-Battle', 'Stream-Punkte', 'Hot Words', 'Website-Builder', 'Casino-Deals', 'Live-Chat'],
      stats: [
        { value: '14+', label: 'Stream-Tools' },
        { value: '10+', label: 'OBS-Overlays' },
        { value: '100%', label: 'Kostenlos starten' },
      ],
      featuresSection: {
        label: 'Features', title: 'Alles was du zum Streamen brauchst',
        items: [
          { t: 'Wager Tracker', d: 'Dynamischer Wager-Fortschritt mit Farbwechsel-Balken und Live-Multiplikator.' },
          { t: 'Bonus Hunt', d: 'Kompletter Tracker mit Buy-in, Auto-Multiplikatoren und Required X.' },
          { t: 'Turniere', d: 'Bracket-System für bis zu 32 Spieler mit Glücksrad.' },
          { t: 'Boss Fight', d: 'Gauntlet-Modus — Boss gegen Herausforderer in Einzel-Duellen.' },
          { t: 'Slot-Anfragen', d: 'Zuschauer schlagen Spiele per !sr vor. Verlosung wählt den Gewinner.' },
          { t: 'Persönliche Bestleistungen', d: 'Auto-Rangliste aus deiner Bonushunt-Historie.' },
          { t: 'Punkte-Battle', d: 'Wett-Pools bei denen Zuschauer per !bet Befehl setzen.' },
          { t: 'Stream-Punkte', d: 'Loyalitätssystem mit Verdienst, Ranglisten und Shop.' },
          { t: 'Vorhersagen', d: 'Zahlenraten + A gegen B Abstimmung mit Live-Overlays.' },
          { t: 'Hot Words', d: 'Echtzeit Chat-Wort-Häufigkeit mit Badge-Overlay.' },
          { t: 'Twitch-Bot', d: 'Integrierter IRC-Bot mit allen Befehlen und Chat-Relay.' },
          { t: 'Website-Builder', d: 'Persönliche Streamer-Seite mit Casino-Deals.' },
          { t: 'Verlosung', d: 'Zuschauer treten bei, du drehst. Animierte Gewinner-Enthüllung.' },
          { t: 'Live-Chat', d: 'Chat-Overlay mit Rollen-Badges. Twitch + Kick.' },
        ],
      },
      why: {
        label: 'Warum Pulseframelabs', title: 'Anders gebaut',
        items: [
          { title: 'Alles-in-Einem', desc: 'Kein Jonglieren mit 5 verschiedenen Tools mehr. Overlays, Bot, Punkte, Website — alles in einem Dashboard. Einmal konfigurieren, überall streamen.' },
          { title: 'Echtzeit überall', desc: 'Jedes Overlay aktualisiert sich sofort. Wenn du einen Turnier-Gewinner wählst, den Wager anpasst oder ein Zuschauer wettet — das Overlay zeigt es live. Keine Verzögerung.' },
          { title: 'Zuschauer-Interaktion', desc: 'Dein Publikum ist Teil der Show. Sie treten Turnieren bei, schlagen Slots vor, platzieren Wetten, stimmen ab und sammeln Punkte — alles über einfache Chat-Befehle.' },
          { title: 'Professionelle Overlays', desc: '10+ thematische OBS-Overlays die Premium aussehen. Wager-Balken, Bracket-Bäume, Bossfight-Gauntlets, Chat-Displays, Hot-Word-Clouds — alles anpassbar.' },
          { title: 'Integrierter Twitch-Bot', desc: 'Kein externer Bot nötig. Unser IRC-Bot handhabt !sr, !join, !bet, !vote, !points und eigene Befehle. Verbindet sich in Sekunden via OAuth.' },
          { title: 'Deine eigene Website', desc: 'Erstelle eine persönliche Streamer-Landingpage mit Casino-Deals, Social-Links und animiertem Partikel-Hintergrund. Teile einen Link für alles.' },
        ],
      },
      commands: {
        label: 'Chat-Befehle', title: 'Deine Zuschauer bestimmen die Action',
        sub: 'Einfache Chat-Befehle die jeder nutzen kann. Kein Setup für Zuschauer nötig.',
        items: [
          { cmd: '!sr', args: 'Spielname', desc: 'Ein Slot-Spiel für den Streamer vorschlagen' },
          { cmd: '!join', args: 'Spielname', desc: 'Einem Turnier, Bossfight oder einer Verlosung beitreten' },
          { cmd: '!bet', args: 'Option Betrag', desc: 'Einen Punkte-Einsatz in einem aktiven Battle platzieren' },
          { cmd: '!vote', args: 'a / b', desc: 'Bei einer Vorhersage abstimmen (Option A oder B)' },
          { cmd: '!points', args: '', desc: 'Deinen aktuellen Punktestand abfragen' },
          { cmd: '!sr cancel', args: '', desc: 'Deine Slot-Anfrage aus der Warteschlange entfernen' },
        ],
      },
      setupSection: {
        label: 'Setup', title: 'Von Null zum Livestream',
        items: [
          { n: '01', t: 'Konto erstellen', d: 'Kostenlos in Sekunden registrieren. Keine Kreditkarte nötig.', time: '30s' },
          { n: '02', t: 'Twitch verbinden', d: 'Deinen Kanal per OAuth-Token über den Setup-Wizard verknüpfen.', time: '1min' },
          { n: '03', t: 'Tools konfigurieren', d: 'Overlays, Bot-Befehle und Features über das Dashboard einrichten.', time: '1min' },
          { n: '04', t: 'Overlays hinzufügen', d: 'Overlay-URLs als Browser-Quellen in OBS einfügen. Komplett gestylt.', time: '30s' },
          { n: '05', t: 'Zuschauer einbinden', d: 'Zuschauer interagieren per !join, !sr, !bet, !vote im Chat.', time: 'Live' },
          { n: '06', t: 'Live gehen', d: 'Stream starten. Alle Overlays aktualisieren sich in Echtzeit.', time: 'Bereit' },
        ],
      },
      pricing: {
        label: 'Preise', title: 'Wähle deinen Plan',
        sub: 'Credits kaufen, Plan wählen. Alle Features in jedem Paket enthalten.',
        trial: 'Testversion', trialDesc: 'Teste alle Features für 24 Stunden',
        monthly: 'Monatlich', monthlyDesc: 'Voller Zugang, jederzeit kündbar',
        quarterly: 'Vierteljährlich', quarterlyDesc: '15% sparen — am flexibelsten',
        halfYear: 'Halbjährlich', halfYearDesc: '25% sparen — bestes Preis-Leistung',
        annual: 'Jährlich', annualDesc: '35% sparen — ultimativer Deal',
        perMonth: '/Mo', save: 'Spare',
        credits: 'Credits',
        day: '1 Tag', month: '1 Monat', months3: '3 Monate', months6: '6 Monate', months12: '12 Monate',
        allFeatures: 'Alle Features inklusive',
        features: ['Alle 14+ Stream-Tools', 'Alle 10+ OBS-Overlays', 'Twitch-Bot mit allen Befehlen', 'Website-Builder', 'Unbegrenzte Turniere & Boss Fights', 'Stream-Punkte & Shop-System'],
        popular: 'Beliebtester Plan',
        cryptoNote: 'Credits mit Kryptowährung kaufen — dann Plan aktivieren',
        howItWorks: 'So funktioniert es',
        step1: 'Kostenlos registrieren & Dashboard erkunden',
        step2: 'Credits mit Krypto kaufen (BTC, ETH, USDT...)',
        step3: 'Plan wählen & mit Credits aktivieren',
        step4: 'Alle Overlay-Links & Features sofort freigeschaltet',
        choosePlan: 'Plan wählen',
        registerFree: 'Kostenlos registrieren',
        freeNote: 'Kostenlose Registrierung — alle Features erkunden. Overlay-Links werden nach Kauf eines Plans mit Credits freigeschaltet.',
      },
      ctaSection: {
        label: 'Loslegen', title: 'Bereit All-In zu gehen?',
        sub: 'Registriere dich kostenlos, erkunde das Dashboard und schalte alles mit Credits frei wenn du bereit bist.',
        cta: 'Jetzt kostenlos registrieren',
      },
      footer: 'Alle Rechte vorbehalten.',

      testimonials: {
        label: 'Vertraut von Streamern', title: 'Was Streamer sagen',
        items: [
          { name: 'CasinoKing', role: 'Casino-Streamer', text: 'Pulseframelabs hat 5 verschiedene Tools für mich ersetzt. Die Overlays sehen genial aus und der Bot funktioniert einfach.' },
          { name: 'SlotMaster', role: 'Slot-Streamer', text: 'Allein der Bonushunt-Tracker ist es wert. Meine Zuschauer lieben das Turnier-Bracket-Overlay.' },
          { name: 'HighRollerTV', role: 'Casino-Streamer', text: 'Setup hat 5 Minuten gedauert. Der Website-Builder hat mir erspart einen Entwickler zu engagieren. Sehr empfehlenswert.' },
        ],
      },

      faq: {
        label: 'FAQ', title: 'Häufig gestellte Fragen',
        items: [
          { q: 'Wie funktioniert die Zahlung?', a: 'Du kaufst Credits mit Kryptowährung (BTC, ETH, LTC, USDT). Credits werden sofort nach Blockchain-Bestätigung gutgeschrieben. Dann aktivierst du einen Plan mit deinen Credits.' },
          { q: 'Kann ich jederzeit kündigen?', a: 'Es gibt kein wiederkehrendes Abo. Du kaufst einen Plan einmalig und er läuft bis zum Ablauf. Keine automatische Verlängerung, keine versteckten Kosten.' },
          { q: 'Welche OBS-Version wird unterstützt?', a: 'Jede Version von OBS Studio die Browser-Quellen unterstützt. Einfach die Overlay-URL kopieren und als Browser-Quelle hinzufügen.' },
          { q: 'Kann ich vor dem Kauf testen?', a: 'Ja! Registriere dich kostenlos und erkunde das gesamte Dashboard. Overlay-Links werden nach dem Kauf eines Plans freigeschaltet.' },
          { q: 'Wie viele Overlays kann ich nutzen?', a: 'Alle Pläne beinhalten jedes Overlay und Feature. Es gibt keine Stufen-Beschränkungen — du bekommst alles.' },
          { q: 'Sind meine Daten privat?', a: 'Ja. Jeder Nutzer hat isolierte Daten mit Row Level Security. Niemand kann deine Einstellungen, Overlays oder Konfigurationen sehen.' },
        ],
      },

      liveCounter: {
        label: 'Community', title: 'Wächst jeden Tag',
        streamers: 'Registrierte Streamer',
        overlays: 'Erstellte Overlays',
        uptime: 'Verfügbarkeit',
      },

      comparison: {
        label: 'Vergleich', title: 'Kostenlos vs. Premium',
        free: 'Kostenlos', premium: 'Premium',
        features: [
          { name: 'Dashboard-Zugang', free: true, premium: true },
          { name: 'Alle 14+ Stream-Tools', free: true, premium: true },
          { name: 'OBS Overlay-Links', free: false, premium: true },
          { name: 'Twitch-Bot Verbindung', free: false, premium: true },
          { name: 'Öffentliche Streamer-Seite', free: false, premium: true },
          { name: 'Website-Builder', free: false, premium: true },
          { name: 'Store / Punkte-System', free: false, premium: true },
          { name: 'Theme-Anpassung', free: true, premium: true },
          { name: 'Prioritäts-Support', free: false, premium: true },
        ],
      },
    },

    // ── Login page ────────────────────────────────────────────────────
    login: {
      welcomeBack: 'Willkommen zurück',
      getStarted: 'Jetzt starten',
      signInSub: 'Melde dich an um auf dein Streaming-Dashboard zuzugreifen',
      registerSub: 'Erstelle dein Konto in Sekunden',
      signIn: 'Anmelden',
      register: 'Registrieren',
      email: 'E-Mail',
      password: 'Passwort',
      confirmPassword: 'Passwort bestätigen',
      username: 'Benutzername',
      emailPlaceholder: 'deine@email.com',
      passwordPlaceholder: 'Passwort eingeben',
      createPasswordPlaceholder: 'Sicheres Passwort erstellen',
      repeatPasswordPlaceholder: 'Passwort wiederholen',
      usernamePlaceholder: 'Dein Anzeigename',
      signInBtn: 'Anmelden',
      createAccountBtn: 'Konto erstellen',
      noAccount: 'Noch kein Konto?',
      hasAccount: 'Bereits ein Konto?',
      terms: 'Mit der Nutzung stimmst du unseren Nutzungsbedingungen zu',
      platformOverview: 'Plattform-Übersicht',
      videoSoon: 'Video folgt',
      pwLength: 'Mindestens 8 Zeichen',
      pwUppercase: '1 Großbuchstabe (A-Z)',
      pwSpecial: '1 Sonderzeichen (!@#...)',
      pwNoMatch: 'Passwörter stimmen nicht überein',
      usernameRequired: 'Benutzername ist erforderlich',
      emailRequired: 'E-Mail ist erforderlich',
      pwRequirements: 'Passwort erfüllt nicht die Anforderungen',
      emailSent: 'Bestätigungsmail gesendet!',
      emailSentDesc: 'Wir haben einen Bestätigungslink an deine E-Mail-Adresse gesendet. Bitte prüfe deinen Posteingang und klicke auf den Link um dein Konto zu aktivieren.',
      checkSpam: 'Nicht erhalten? Prüfe deinen Spam-Ordner.',
      resend: 'E-Mail erneut senden',
      resent: 'E-Mail erneut gesendet!',
      emailNotConfirmed: 'Deine E-Mail-Adresse wurde noch nicht bestätigt. Bitte prüfe deinen Posteingang.',
      backToLogin: 'Zurück zur Anmeldung',
    },

    // ── Sidebar ───────────────────────────────────────────────────────
    sidebar: {
      dashboard: 'Dashboard', overlays: 'Overlays', community: 'Community', stream: 'Stream',
      wagerBar: 'Wager Bar', personalBests: 'Persönliche Bestleistungen', slotRequests: 'Slot-Anfragen',
      bonushunt: 'Bonushunt', tournaments: 'Turniere', bossFight: 'Boss Fight',
      hotWords: 'Hot Words', predictions: 'Vorhersagen', join: 'Beitreten', chat: 'Chat',
      twitchBot: 'Twitch-Bot', pointsBattle: 'Punkte-Battle', streamPoints: 'Stream-Punkte',
      website: 'Webseite', shop: 'Shop', credits: 'Guthaben',
      lightMode: 'Hell-Modus', darkMode: 'Dunkel-Modus', signOut: 'Abmelden',
    },

    // ── Shop ──────────────────────────────────────────────────────────
    shop: {
      title: 'Shop',
      creditBalance: 'Guthaben', credits: 'Credits',
      buyCredits: 'Credits kaufen',
      cryptoNote: 'Bezahle mit Kryptowährung — Credits werden nach Bestätigung gutgeschrieben.',
      plans: 'Abonnement-Pakete', activePlan: 'Aktives Paket',
      noPlan: 'Kein aktives Paket',
      activate: 'Aktivieren', activated: 'Aktiviert!',
      insufficientCredits: 'Nicht genug Credits',
      expiresIn: 'Läuft ab in', days: 'Tagen',
      transactionHistory: 'Transaktionsverlauf',
      purchase: 'Credit-Kauf', planActivation: 'Paket-Aktivierung',
      trial: 'Testpaket', monthly: 'Monatlich', quarterly: 'Vierteljährlich', halfYear: 'Halbjährlich', annual: 'Jährlich',
      trialDesc: '1 Tag Zugang', monthlyDesc: '30 Tage Zugang', quarterlyDesc: '90 Tage Zugang',
      halfYearDesc: '180 Tage Zugang', annualDesc: '365 Tage Zugang',
      activateToUnlock: 'Aktiviere ein Paket zum Freischalten',
      urlHidden: 'Abonniere um deine OBS-URL anzuzeigen',
      pageNotAvailable: 'Diese Seite ist nicht verfügbar. Der Besitzer hat kein aktives Abonnement.',
      payWithCrypto: 'Bezahlen mit BTC, ETH, LTC, USDT',
      selectCoin: 'Kryptowährung wählen',
      generating: 'Adresse wird generiert...',
      generateAddress: 'Zahlungsadresse generieren',
      sendPayment: 'Zahlung senden',
      amountToPay: 'Zu zahlender Betrag',
      sendTo: 'An diese Adresse senden',
      copyLabel: 'Kopieren', copiedLabel: 'Kopiert',
      waitingPayment: 'Warte auf Zahlungsbestätigung...',
      autoCredit: 'Credits werden nach Bestätigung automatisch gutgeschrieben.',
    },

    // ── Dashboard ─────────────────────────────────────────────────────
    dashboard: {
      morning: 'Guten Morgen', afternoon: 'Guten Nachmittag', evening: 'Guten Abend',
      welcomeMsg: 'Wir wünschen dir viel Glück und Erfolg an einem neuen Streaming-Tag!',
      supportMsg: 'Bei Fragen wende dich bitte an unseren Support über den Live-Chat unten rechts auf dem Bildschirm.',
      quickActions: 'Schnellaktionen',
      actions: {
        wagerBar: 'Wager-Fortschritt verfolgen', personalBests: 'Beste Gewinne ansehen', slotRequests: 'Slot-Anfragen verwalten',
        bonushunt: 'Bonushunts erstellen', tournaments: 'Turniere veranstalten', bossFight: 'Gauntlet-Modus starten',
        hotWords: 'Chat-Wörter verfolgen', predictions: 'Raten & Abstimmen', join: 'Zuschauer-Verlosung',
        chat: 'Live-Chat-Overlay', twitchBot: 'Bot-Verbindung & Befehle', pointsBattle: 'Zuschauer-Wetten mit Punkten',
        streamPoints: 'Punktesystem & Shop', website: 'Deine Streamer-Webseite bauen',
      },
    },

    // ── Wager Bar ─────────────────────────────────────────────────────
    wager: {
      title: 'Wager Bar',
      infoText: 'Verfolge deinen Wager-Fortschritt für Casino-Boni. Gib Einzahlung, Bonus und Wager-Ziel ein. Der Fortschrittsbalken zeigt den Live-Status und ändert die Farbe (rot zu orange zu grün). Multiplikator und verbleibender Betrag werden automatisch berechnet.',
      newWager: 'Neuer Wager',
      newWagerSession: 'Neue Wager-Sitzung',
      casinoName: 'Casino-Name *',
      bonusType: 'Bonus-Typ',
      nonSticky: 'Non-Sticky', sticky: 'Sticky',
      currency: 'Währung',
      depositAmount: 'Einzahlungsbetrag',
      bonusAmount: 'Bonusbetrag',
      wagerAmount: 'Wager-Betrag',
      noSessions: 'Noch keine Wager-Sitzungen. Erstelle deine erste oben.',
      valueColors: 'Wertfarben', win: 'Gewinn', loss: 'Verlust',
    },

    // ── Personal Bests ────────────────────────────────────────────────
    personalBests: {
      title: 'Persönliche Bestleistungen',
      infoText: 'Zeigt automatisch die besten Gewinne pro Spiel aus allen Bonushunts. Einträge werden nach Spielname gruppiert — für jedes Spiel werden der höchste Gewinn und die Anzahl der Auftritte angezeigt. Das Overlay kann als Browser-Quelle in OBS eingebettet werden.',
      totalGames: 'Spiele gesamt', bestWin: 'Bester Gewinn', totalPlays: 'Spiele gesamt', avgWin: 'Ø Gewinn',
      highestWin: 'Höchster Gewinn', mostPlayed: 'Am meisten gespielt',
      searchGame: 'Spiel suchen...',
      colGame: 'Spiel', colBestWin: 'Bester Gewinn', colAppearances: 'Auftritte', colWinBar: 'Gewinnbalken',
      empty: 'Noch keine Gewinne in Bonushunts. Erstelle einen Bonushunt und trage Gewinne ein.',
    },

    // ── Slot Requests ─────────────────────────────────────────────────
    slotRequests: {
      title: 'Slot-Anfragen',
      infoText: 'Zuschauer können Slot-Anfragen per !sr Spielname im Chat senden. Die Liste zeigt alle Anfragen. Nutze den Verlosung-Button um zufällig ein Spiel auszuwählen. Du kannst Anfragen jederzeit öffnen/schließen und die Liste leeren.',
      newRequest: 'Neue Anfrage',
      viewerName: 'Zuschauername',
      egGame: 'z.B. Sweet Bonanza',
      raffle: 'Verlosung', rolling: 'Wird gelost...', reRoll: 'Nochmal losen',
      confirmClear: 'Bestätigen & Liste leeren', confirmKeep: 'Bestätigen & Behalten',
      empty: 'Keine Slot-Anfragen. Manuell hinzufügen oder !sr im Chat nutzen.',
      pendingTotal: 'Offen / Gesamt', won: 'Gewonnen',
      raffleInProgress: 'Verlosung läuft...',
    },

    // ── Bonushunt ─────────────────────────────────────────────────────
    bonushunt: {
      title: 'Bonushunt',
      infoText: 'Verwalte deine Bonushunts mit Startguthaben, Buy-in pro Spiel und automatischer Multiplikator-Berechnung. Das Overlay zeigt den Live-Fortschritt, Required X und den aktuellen Status. Als Browser-Quelle in OBS einbettbar.',
      newBonushunt: 'Neuer Bonushunt',
      huntName: 'Hunt-Name',
      startBalance: 'Startguthaben',
      completed: 'Abgeschlossen',
      empty: 'Noch keine Bonushunts. Erstelle deinen ersten oben.',
      showTitle: 'Titel anzeigen', showProfit: 'Profit anzeigen',
      showTotalWin: 'Gesamtgewinn anzeigen', showNumbers: 'Nummern anzeigen',
      valueColors: 'Wertfarben', win: 'Gewinn', loss: 'Verlust',
    },

    // ── Tournaments ───────────────────────────────────────────────────
    tournaments: {
      title: 'Turnier',
      infoText: 'Erstelle Turniere mit bis zu 32 Spielern. Zuschauer können per !join Spielname im Chat beitreten. Nach der Beitrittsphase werden die Spieler im Bracket platziert. Klicke auf das Pokal-Symbol um Gewinner weiterzuleiten. Das Overlay zeigt den kompletten Bracket-Baum live.',
      newTournament: 'Neues Turnier',
      tournamentName: 'Turniername',
      participants4: '4 Teilnehmer', participants8: '8 Teilnehmer',
      participants16: '16 Teilnehmer', participants32: '32 Teilnehmer',
      participants: 'Teilnehmer', gameName: 'Spielname',
      noParticipants: 'Noch keine Teilnehmer. Manuell hinzufügen oder Zuschauer können !join im Chat nutzen.',
      luckyWheel: 'Glücksrad', setBoss: 'Boss setzen',
      startTournament: 'Turnier starten',
      champion: 'Champion:', winnerLabel: 'Gewinner:',
      clickTrophy: 'Klicke auf das Pokal-Symbol neben einem Spieler im Overlay um den Gewinner zu wählen.',
      empty: 'Noch keine Turniere. Erstelle dein erstes oben.',
      highlightFinal: 'Highlight / Finale',
      showPrizePool: 'Preispool anzeigen', showSlots: 'Slots anzeigen', showStatus: 'Status anzeigen',
    },

    // ── Boss Fight ────────────────────────────────────────────────────
    bossfight: {
      title: 'Boss Fight',
      infoText: 'Boss Fight im Gauntlet-Modus: Ein Boss kämpft gegen mehrere Herausforderer in 1v1-Duellen. Der Boss startet mit so vielen Leben wie es Herausforderer gibt. Zuschauer treten per !join Spielname bei. Nach dem Start entscheidest du jedes Duell mit Boss gewinnt / Herausforderer gewinnt.',
      newBossfight: 'Neuer Boss Fight',
      name: 'Name',
      addParticipant: 'Teilnehmer hinzufügen',
      participants: 'Teilnehmer',
      noParticipants: 'Noch keine Teilnehmer. Manuell hinzufügen oder Zuschauer können !join Spielname im Chat eingeben.',
      setBoss: 'Boss setzen', startFight: 'Kampf starten', luckyWheel: 'Glücksrad',
      currentDuel: 'Aktuelles Duell', challenger: 'Herausforderer', vs: 'VS', boss: 'Boss',
      bossWins: 'Boss gewinnt', challengerWins: 'Herausforderer gewinnt',
      bossLives: 'Boss-Leben:', score: 'Punktestand: Spieler',
      duelHistory: 'Duell-Verlauf',
      bossWon: 'Boss gewonnen', challengerWon: 'Herausforderer gewonnen',
      bossWinsTitle: 'BOSS GEWINNT!', playersWinTitle: 'SPIELER GEWINNEN!',
      finalScore: 'Endergebnis: Spieler',
      completeRemove: 'Abschließen & Entfernen',
      empty: 'Noch keine Boss Fights. Erstelle deinen ersten oben.',
    },

    // ── Hot Words ─────────────────────────────────────────────────────
    hotwords: {
      title: 'Hot Words',
      infoText: 'Hot Words verfolgt automatisch die häufigsten Wörter aus dem Twitch-Chat. Der Bot zählt jedes Wort in jeder Nachricht. Nutze den Wortfilter um unerwünschte Wörter auszuschließen.',
      empty: 'Keine Hot Words. Verbinde den Twitch-Bot um Chat-Wörter zu verfolgen.',
      totalWords: 'Wörter gesamt', totalMentions: 'Erwähnungen gesamt', topWord: 'Top-Wort',
      wordList: 'Wortliste', clearAll: 'Alle löschen',
      wordFilter: 'Wortfilter', excludedWords: 'Ausgeschlossene Wörter',
      filterPlaceholder: 'wort1, wort2, wort3',
      maxEntries: 'Max. Einträge',
    },

    // ── Predictions ───────────────────────────────────────────────────
    predictions: {
      title: 'Vorhersagen',
      infoText: 'Vorhersagen bietet zwei Modi: Beim Ratespiel tippen Zuschauer eine Zahl im Chat — der nächste Tipp gewinnt. Bei der Vorhersage-Wand stimmen Zuschauer zwischen zwei Optionen ab. Beide Modi können als Overlays in OBS eingebettet werden.',
      newPrediction: 'Neue Vorhersage',
      guessingGame: 'Ratespiel', predictionWall: 'Vorhersage-Wand',
      noActive: 'Keine aktive Vorhersage. Erstelle eine neue oben.',
      noActiveGuess: 'Kein aktives Ratespiel. Erstelle eines mit dem Button oben.',
      guessesReceived: 'Tipps erhalten',
      number: 'Zahl', targetValue: 'Zielwert', resolve: 'Auflösen',
      results: 'Ergebnisse', newGuessingGame: 'Neues Ratespiel',
      question: 'Frage', egWho: 'z.B. Wer gewinnt?',
      optionA: 'Option A', optionB: 'Option B',
      startPrediction: 'Vorhersage starten', lockVoting: 'Abstimmung sperren',
      optionAWins: 'Option A gewinnt', optionBWins: 'Option B gewinnt',
    },

    // ── Join ──────────────────────────────────────────────────────────
    join: {
      title: 'Beitreten',
      infoText: 'Öffne eine Beitritts-Sitzung und Zuschauer können per !join im Chat teilnehmen. Nach dem Schließen wird ein Gewinner zufällig gezogen — mit einer animierten Namensanzeige im Overlay.',
      newJoin: 'Neue Runde',
      noActive: 'Keine aktive Beitritts-Sitzung. Erstelle eine neue oben.',
      closeJoin: '!join schließen', drawWinner: 'Gewinner ziehen', newRound: 'Neue Runde',
      drawing: 'Wird gezogen...',
      participants: 'Teilnehmer',
      noParticipants: 'Noch keine Teilnehmer. Zuschauer können per !join im Chat beitreten.',
      addManually: 'Manuell hinzufügen',
    },

    // ── Chat ──────────────────────────────────────────────────────────
    chat: {
      title: 'Live-Chat-Overlay',
      infoText: 'Dieses Overlay liest den Chat live und integriert auch den Kick-Chat über Restream. Es wird direkt in OBS als Browser-Quelle eingebettet — deine Zuschauer sehen nicht dieses Dashboard, nur das Overlay im Stream.',
      newChat: 'Neuer Chat',
      name: 'Name',
      empty: 'Noch keine Chats. Erstelle deinen ersten oben.',
      chatEffects: 'Chat & Effekte', maxMessages: 'Max. Nachrichten',
    },

    // ── Twitch Bot ────────────────────────────────────────────────────
    twitchBot: {
      title: 'Twitch-Bot',
      infoText: 'Verbinde deinen Twitch-Kanal per IRC und OAuth-Token. Der Bot liest den Chat, reagiert auf Befehle (!sr, !join) und leitet Nachrichten an Overlays weiter. Eigene Befehle und Feature-Schalter können hier verwaltet werden.',
      newBot: 'Neuer Twitch-Bot',
      twitchChannel: 'Twitch-Kanal',
      enterChannel: 'Gib deinen Kanalnamen ein',
      channelName: 'Kanalname *', channelPlaceholder: 'dein_twitch_kanal',
      botUsername: 'Bot-Benutzername (optional)', botPlaceholder: 'bot_konto (leer = gleich wie Kanal)',
      botHint: 'Wenn du ein separates Bot-Konto hast, gib es hier ein.',
      next: 'Weiter', back: 'Zurück', completeSetup: 'Setup abschließen',
      setupChannel: 'Kanal einrichten',
      oauthToken: 'OAuth-Token', oauthSetup: 'Bot-Zugang einrichten',
      oauthInfo: 'Der OAuth-Token erlaubt dem Bot in deinem Namen Nachrichten zu schreiben und auf Chat-Events zu reagieren. Generiere ihn auf twitchapps.com/tmi und füge ihn hier ein.',
      oauthPlaceholder: 'oauth:xxxxxxxxxxxxxxx',
      oauthLocal: 'Der Token wird nur lokal gespeichert und nicht geteilt.',
      empty: 'Noch kein Twitch-Bot eingerichtet. Erstelle deinen ersten oben.',
      connection: 'Verbindung', channel: 'Kanal',
      connect: 'Verbinden', disconnect: 'Trennen',
      featureToggles: 'Feature-Schalter',
      chatRelay: 'Chat-Relay', chatRelayDesc: 'Alle Twitch-Chat-Nachrichten an Overlays weiterleiten',
      slotRequestsToggle: 'Slot-Anfragen', slotRequestsDesc: '!sr <Spiel> Befehle von Zuschauern verarbeiten',
      quickGuesses: 'Schnelle Tipps', quickGuessesDesc: 'Tipp-Befehle von Zuschauern verarbeiten',
      pointsBattleToggle: 'Punkte-Battle', pointsBattleDesc: '!bet Befehle für Vorhersagen verarbeiten',
      loyaltyGiveaways: 'Treue-Verlosungen', loyaltyGiveawaysDesc: 'Schlüsselwort-Einträge für Verlosungen verfolgen',
      customCommands: 'Eigene Befehle',
      commandPlaceholder: '!befehl', responsePlaceholder: 'Antworttext',
      noCommands: 'Noch keine Befehle.',
      liveFeed: 'Live-Feed', clear: 'Leeren',
      connectToSee: 'Verbinde den Bot um den Live-Chat zu sehen.',
      connectTwitch: 'Mit Twitch verbinden',
      twitchConnected: 'Twitch erfolgreich verbunden',
    },

    // ── Points Battle ─────────────────────────────────────────────────
    pointsBattle: {
      title: 'Punkte-Battle',
      infoText: 'Erstelle ein Vorhersage-Battle mit eigenen Optionen. Zuschauer setzen Punkte per !bet Schlüsselwort Betrag im Chat. Wenn der Timer abläuft werden Wetten gesperrt. Richte mindestens 2 Optionen mit eindeutigen Schlüsselwörtern ein.',
      newBattle: 'Neues Battle', newPointsBattle: 'Neues Punkte-Battle',
      options: 'Optionen (min. 2)',
      keywordPlaceholder: 'Schlüsselwort (z.B. rot)', labelPlaceholder: 'Label (z.B. Team Rot)',
      addOption: '+ Option hinzufügen',
      minPoints: 'Min. Punkte', maxPoints: 'Max. Punkte', duration: 'Dauer (Sek.)',
      startBattle: 'Battle starten',
      noActive: 'Kein aktives Battle. Erstelle eines oben.',
      stop: 'Stopp', totalPool: 'Gesamtpool', bettors: 'Wetter',
      command: 'Befehl', bets: 'Wetten', pts: 'Pkt.',
      recentBets: 'Letzte Wetten',
    },

    // ── Stream Points ─────────────────────────────────────────────────
    streamPoints: {
      title: 'Stream-Punkte & Shop',
      infoText: 'Verwalte Zuschauer-Punkte und einen Shop. Zuschauer verdienen Punkte durch Watchtime und Interaktionen. Sie können ihren Kontostand mit !points im Chat abfragen. Erstelle Shop-Artikel die Zuschauer mit ihren Punkten einlösen können.',
      newStreamPoints: 'Neue Stream-Punkte',
      empty: 'Noch keine Stream-Punkte konfiguriert. Erstelle dein Setup oben.',
      points: 'Punkte', store: 'Shop',
      pointsConfig: 'Punkte-Konfiguration',
      pointsPerMinute: 'Punkte pro Minute', pointsPerFollow: 'Punkte pro Follow', pointsPerSub: 'Punkte pro Sub',
      viewers: 'Zuschauer', totalPoints: 'Punkte gesamt',
      noViewers: 'Keine Zuschauer. Sie registrieren sich mit !points im Chat.',
      newStoreItem: 'Neuer Shop-Artikel', addStoreItem: 'Shop-Artikel hinzufügen',
      itemName: 'Artikelname *', egItem: 'z.B. VIP-Abzeichen',
      pricePoints: 'Preis (Punkte) *',
      quantity: 'Menge (-1 = unbegrenzt)',
      visible: 'Sichtbar', hidden: 'Versteckt',
      description: 'Beschreibung', itemDesc: 'Artikelbeschreibung...',
      createItem: 'Artikel erstellen', storeItems: 'Shop-Artikel',
      noStoreItems: 'Keine Shop-Artikel. Füge einen oben hinzu.',
      unlimited: '∞', left: 'übrig',
      redemptions: 'Einlösungen',
      completed: 'abgeschlossen', refunded: 'erstattet', pending: 'ausstehend',
      itemImage: 'Artikelbild', imageHint: 'PNG/JPG, max 512 KB',
    },

    // ── Website ───────────────────────────────────────────────────────
    website: {
      branding: 'Branding', colors: 'Farben', icon: 'Icon',
      sections: 'Bereiche', socials: 'Socials', deals: 'Deals', preview: 'Vorschau',
      websiteTitle: 'Webseiten-Titel *', egStreamer: 'z.B. StreamerName',
      tagline: 'Slogan', egTagline: 'z.B. Casino-Streamer & Content Creator',
      colorTheme: 'Farbthema',
      gold: 'Gold', purple: 'Lila', blue: 'Blau', emerald: 'Smaragd',
      red: 'Rot', cyan: 'Cyan', pink: 'Pink', orange: 'Orange',
      customColor: 'Eigene Primärfarbe',
      chooseIcon: 'Icon wählen',
      globe: 'Globus', gamepad: 'Gamepad', zap: 'Blitz', crown: 'Krone',
      star: 'Stern', diamond: 'Diamant', flame: 'Flamme', trophy: 'Pokal',
      uploadIcon: 'Oder eigenes Icon hochladen',
      uploadHint: 'Empfohlene Größe: 128 x 128 px — Min: 64x64 px, Max: 512x512 px. PNG oder SVG mit transparentem Hintergrund.',
      clickUpload: 'Klicken zum Hochladen (PNG, SVG)',
      iconUploaded: 'Icon hochgeladen', removeIcon: 'Eigenes Icon entfernen',
      websiteSections: 'Webseiten-Bereiche',
      aboutMe: 'Über mich', aboutMeDesc: 'Kurze Bio und Vorstellung',
      schedule: 'Stream-Zeitplan', scheduleDesc: 'Wöchentliche Streaming-Zeiten',
      socialLinks: 'Social Links', socialLinksDesc: 'Twitch, YouTube, Twitter, etc.',
      stats: 'Statistiken', statsDesc: 'Follower-Anzahl, Stream-Stunden',
      gallery: 'Galerie', galleryDesc: 'Clips und Highlights',
      donate: 'Spenden', donateDesc: 'Spendenlink und Ziele',
      casinoDeals: 'Casino-Deals', casinoDealsDesc: 'Casino-Angebote und Bonus-Deals',
      twitch: 'Twitch', youtube: 'YouTube', twitter: 'Twitter/X',
      instagram: 'Instagram', discord: 'Discord', tiktok: 'TikTok', kick: 'Kick',
      myWebsite: 'Meine Webseite', welcomeStream: 'Willkommen zu meinem Stream', playNow: 'Jetzt spielen',
      newWebsite: '+ Neue Webseite', editWebsite: 'Webseite bearbeiten', reset: 'Zurücksetzen', cancel: 'Abbrechen', saveWebsite: 'Webseite speichern',
      websiteBuilder: 'Website-Builder',
      websiteBuilderInfo: 'Erstelle deine persönliche Streamer-Landingpage mit Casino-Deals, Social-Links und einem eigenen Design. Deine Seite ist öffentlich erreichbar und kann mit einem Link geteilt werden.',
      empty: 'Noch keine Webseite erstellt. Klicke auf "+ Neue Webseite" um zu starten.',
      copy: 'Kopieren', open: 'Öffnen', websitePreview: 'Live-Vorschau', primaryColor: 'Primärfarbe',
      casinoDealsInfo: 'Füge Casino-Deals mit Logos, Links und eigenem Button-Text hinzu. Diese werden auf deiner öffentlichen Streamer-Seite angezeigt.',
      addDeal: 'Neuen Deal hinzufügen',
      casinoLogo: 'Casino-Logo (max 200 KB)',
      chooseImage: 'Klicken zum Hochladen',
      dealHeadline: 'Casino-Name / Überschrift',
      dealBtnText: 'Button-Text (Standard: Jetzt spielen)',
      dealLinkUrl: 'Affiliate-Link URL',
      untitledDeal: 'Unbenannter Deal',
      noLink: 'Kein Link gesetzt',
      bgColor: 'Hintergrundfarbe',
      textColorSite: 'Textfarbe',
      accentColorSite: 'Akzentfarbe',
      particles: 'Partikel-Animation',
      showNavbar: 'Navigation anzeigen',
      showFooter: 'Footer anzeigen',
      navBlur: 'Navigation Blur',
      navStyle: 'Navigation-Stil',
      aboutPlaceholder: 'Schreibe eine kurze Bio über dich...',
      scheduleDay: 'Tag', scheduleTime: 'Uhrzeit', addScheduleEntry: 'Eintrag hinzufügen',
      statLabel: 'Bezeichnung', statValue: 'Wert', addStat: 'Statistik hinzufügen',
      galleryUrl: 'Bild- oder Clip-URL', addGalleryItem: 'Bild/Clip hinzufügen',
      donateLink: 'Spenden-Link URL', donateText: 'Spendeninfo-Text...',
    },
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(STORAGE_KEY) || 'en')

  const toggle = () => {
    const next = lang === 'en' ? 'de' : 'en'
    setLang(next)
    localStorage.setItem(STORAGE_KEY, next)
  }

  const t = i18n[lang]

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
